version: '3.3'

services:
  postgres:
    container_name: postgres-docker
    image: postgres:alpine
    restart: on-failure
    environment:
      - POSTGRES_DB=appdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 15432:5432
    volumes:
      - $HOME/docker/volumes/app-postgres:/var/lib/postgresql/data
  app-server:
    build:
      context: ./server
      dockerfile: Server.Dockerfile
    container_name: app-server
    ports:
      - "8080:80"
